### ISSUE TITLE
JSdoc is down

### ISSUE THREAD

**Issue by MattiSG** [OpenTermsArchive/docs#100]
CI is [failing](https://github.com/OpenTermsArchive/docs/actions/runs/7033104593/job/19138196997?pr=99) because of a broken link to https://docs.opentermsarchive.org/jsdoc/. There is no documentation in the README on how to deploy the JSdoc, so I am not sure how to fix it. Should I just run `npm run jsdoc`? How do I deploy? Should the tests even run on the live website rather than on the locally compiled version?

**Comment by clementbiron** [comment]
JSDoc is build and deploy automatically when there is a push on `main` branch or a new engine release.

For some reason, it's seems there is no longer a `/public/jsdoc` folder on the production, i don't know why. And the test workflow doest not build the JSDoc, so testing the absolute links to that documentation could not work. I made a PR to use relative link to the JSDoc in order to be able to run the completed test workflow.

**Comment by MattiSG** [comment]
Unfortunately the fix in #101 did succeed at passing the tests, but not at deploying the JSdoc, which is [still a 404](https://docs.opentermsarchive.org/jsdoc/).

**Comment by clementbiron** [comment]
Fixed with new DNS configuration, see https://docs.opentermsarchive.org/jsdoc/index.html

**Comment by MattiSG** [comment]
🥳  thanks @clementbiron!
